apiVersion: v1
kind: Service
metadata:
  name: python-backend-service
spec:
  type: ClusterIP
  selector:
    app: python-backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080