apiVersion: v1
kind: Service
metadata:
  name: python-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: python-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80